language: node_js
node_js:
  - "6"
env: # required to not break the build when installing node-gyp
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8